-- Market Radar Mobile: first external DB tables
-- Run this once in Supabase SQL Editor.

create table if not exists public.device_watchlists (
  id bigint generated by default as identity primary key,
  device_id text not null,
  stock_name text not null,
  stock_code text,
  sort_order integer not null check (sort_order between 1 and 3),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (device_id, sort_order)
);

create table if not exists public.visitor_logs (
  device_id text not null,
  visit_date date not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  primary key (device_id, visit_date)
);

alter table public.device_watchlists enable row level security;
alter table public.visitor_logs enable row level security;

drop policy if exists "device_watchlists_select_all" on public.device_watchlists;
drop policy if exists "device_watchlists_insert_all" on public.device_watchlists;
drop policy if exists "device_watchlists_update_all" on public.device_watchlists;
drop policy if exists "device_watchlists_delete_all" on public.device_watchlists;

create policy "device_watchlists_select_all"
on public.device_watchlists for select
to anon, authenticated
using (true);

create policy "device_watchlists_insert_all"
on public.device_watchlists for insert
to anon, authenticated
with check (true);

create policy "device_watchlists_update_all"
on public.device_watchlists for update
to anon, authenticated
using (true)
with check (true);

create policy "device_watchlists_delete_all"
on public.device_watchlists for delete
to anon, authenticated
using (true);

drop policy if exists "visitor_logs_select_all" on public.visitor_logs;
drop policy if exists "visitor_logs_insert_all" on public.visitor_logs;
drop policy if exists "visitor_logs_update_all" on public.visitor_logs;

create policy "visitor_logs_select_all"
on public.visitor_logs for select
to anon, authenticated
using (true);

create policy "visitor_logs_insert_all"
on public.visitor_logs for insert
to anon, authenticated
with check (true);

create policy "visitor_logs_update_all"
on public.visitor_logs for update
to anon, authenticated
using (true)
with check (true);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.device_watchlists to anon, authenticated;
grant select, insert, update on public.visitor_logs to anon, authenticated;
